name: WebHooks Members Nuget

on:
  pull_request:
    branches:
      - master
    paths:
      - "WebHooks/src/**"
      - ".github/bcc-webhooks-members-nuget.yml"

env:
  NUGET_API_KEY: oy2ihayrlypzq4mmo7naaoes6a7dxckeraktfdrejllotq

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Add NuGet source 
        run: dotnet nuget add source --username bcc-code --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bcc-code/index.json"

          
      - name: Restore dependencies
        run: dotnet restore WebHooks/src/Bcc.WebHooks.Receivers.Members
        
      - name: Build
        run: dotnet build --no-restore WebHooks/src/Bcc.WebHooks.Receivers.Members

      - name: Pack
        run: dotnet pack --configuration Release WebHooks/src/Bcc.WebHooks.Receivers.Members
        
      - name: Push
        run: dotnet nuget push "WebHooks/src/Bcc.WebHooks.Receivers.Members/bin/Release/Bcc.WebHooks.Receivers.Members.1.0.1.nupkg" --source "github"

#
#
#      - name: publish on version change
#        id: publish_nuget
#        uses: rohith/publish-nuget@v2
#        with:
#          PROJECT_FILE_PATH: WebHooks/src/Bcc.WebHooks.Receivers.Members/Bcc.WebHooks.Receivers.Members.csproj
#          NUGET_KEY: ${{env.NUGET_API_KEY}}
#          PACKAGE_NAME: BccCode.WebHooks.Receivers.Members
          
          
