name: DEV Tenants API - dziala

on: 
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bccplatformdev.azurecr.io
        username: ${{ secrets.acr_bccplatformdev_username }}
        password: ${{ secrets.acr_bccplatformdev_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/bcc-tenants" -f  "bcc-tenants/Bcc.Tenants.Api/Dockerfile" -t bccplatformdev.azurecr.io/bccplatformdev:${{ github.sha }} --label dockerfile-path=bcc-tenants/Bcc.Tenants.Api/Dockerfile
        docker push bccplatformdev.azurecr.io/bccplatformdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bccplatformdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bcc-platform-dev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bcc-platform-dev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bcc-platform-dev
        container-registry-url: bccplatformdev.azurecr.io
        container-registry-username: ${{ secrets.acr_bccplatformdev_username }}
        container-registry-password: ${{ secrets.acr_bccplatformdev_password }}
        secret-name: bccplatformddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: bcc-platform-dev
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          bccplatformdev.azurecr.io/bccplatformdev:${{ github.sha }}
        imagepullsecrets: |
          bccplatformddockerauth
