name: NuGet BuildingBlocks Api

on:
  push:
    branches: [ master ]
    paths:
      - "BuildingBlocks/dotnet/BuildingBlocks**"
      - ".github/workflows/nuget-buildingblock-api.yml"
    
  pull_request:
    branches: [ master ]
    paths:
      - "BuildingBlocks/dotnet/BuildingBlocks**"
      - ".github/workflows/nuget-buildingblock-api.yml"

  workflow_dispatch:

env:
  API_KEY: ${{ secrets.NUGET_API_KEY }}
  CSPROJ_PATH: BuildingBlocks/dotnet/BuildingBlocks.Api/BuildingBlocks.Api.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 6.0.*
            
      inputs:
        varFilePath:
          required: false
          default: ./.github/version.env
          
      - name: Set package version
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' && $GITHUB_EVENT_NAME == 'push' ]]; then
              echo "VERSION=${{ env.VERSION_MAIN }}.${{ github.run_number}}" >> "$GITHUB_ENV"
          else
              echo "VERSION=${{ env.VERSION_MAIN }}.${{ github.run_number}}-beta" >> "$GITHUB_ENV"
          fi
          
      - name: Run Tests
        run: dotnet test ${{ env.CSPROJ_PATH }}
          
      - name: Package
        run: dotnet pack -p:PackageVersion=${{ env.VERSION }} -c Release -o . ${{ env.CSPROJ_PATH }}
  
      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{env.API_KEY}} -s https://api.nuget.org/v3/index.json
               
               
#      - name: publish on version change
#        id: publish_nuget
#        uses: brandedoutcast/publish-nuget@v2.5.5
#        with:
#          PROJECT_FILE_PATH: BuildingBlocks/dotnet/BuildingBlocks.Api/BuildingBlocks.Api.csproj
#          PACKAGE_NAME: Bcc.BuildingBlocks.Api
#          VERSION_STATIC: ${{ env.VERSION }}
#          
#          # Flag to toggle git tagging, enabled by default
#          # TAG_COMMIT: true
#          
#          # Format of the git tag, [*] gets replaced with actual version
#          # TAG_FORMAT: v*
#          
#          NUGET_KEY: ${{env.API_KEY}}
#          
#          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
#          # NUGET_SOURCE: https://api.nuget.org
#          
#          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
#          # INCLUDE_SYMBOLS: false

