name: Build and deploy the Org API to GCP

on:  
  push:
    branches: 
      [ master ]
    paths:
    - bcc-orgs/**
  workflow_dispatch:

env:
  PROJECT_ID: bcc-core-services
  REGISTRY_URL: europe-west1-docker.pkg.dev
  REGISTRY_NAME: org-api
  IMAGE_NAME: default
  APP_BUILD_CONTEXT: bcc-orgs
  APP_DOCKERFILE: bcc-orgs/devops/Dockerfile

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - run: |-
        gcloud --quiet auth configure-docker ${{env.REGISTRY_URL}}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{env.REGISTRY_URL}}/${{env.PROJECT_ID}}/${{env.REGISTRY_NAME}}/${{env.IMAGE_NAME}}:${{ github.sha }}
        context: ${{env.APP_BUILD_CONTEXT}}
        file: ${{env.APP_DOCKERFILE}}

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: defualt
        image: ${{env.REGISTRY_URL}}/${{env.PROJECT_ID}}/${{env.REGISTRY_NAME}}/${{env.IMAGE_NAME}}:${{ github.sha }}