name: Build and deploy the Org API to GCP

on:  
  push:
    branches: 
      [ master ]
    paths:
    - bcc-orgs/**
  workflow_dispatch:

env:
  APP_BUILD_CONTEXT: bcc-orgs
  APP_DOCKERFILE: bcc-orgs/devops/Dockerfile
  IMAGE_NAME: bcc-orgs

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - run: |-
        gcloud --quiet auth configure-docker ${{ secrets.REGISTRY_BASE_URL }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.REGISTRY_BASE_URL }}/${{ secrets.PROJECT_ID}}/${{secrets.REGISTRY_NAME}}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        context: ${{env.APP_BUILD_CONTEXT}}
        file: ${{env.APP_DOCKERFILE}}

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ secrets.ORG_SERVICE_NAME }}
        image: ${{ secrets.REGISTRY_BASE_URL }}/${{ secrets.PROJECT_ID}}/${{secrets.REGISTRY_NAME}}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        region: ${{ secrets.ORG_SERVICE_REGION }}