name: Tenants API Prod Deployment

on:
  push:
    branches:
      - master
    paths:
      - "bcc-tenants/**"
      - ".github/workflows/tenants-api-prod.yml"

env:
  APP_BUILD_CONTEXT: bcc-tenants
  APP_DOCKERFILE: bcc-tenants/Bcc.Tenants.Api/Dockerfile
  APPLICATION_NAME: tenants-api-prod
  ENVIRONMENT: Production
  PORT: 5174
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth SDK
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - run: gcloud --quiet auth configure-docker ${{ secrets.REGISTRY_BASE_URL }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REGISTRY_BASE_URL }}/${{ secrets.GOOGLE_PROJECT_ID}}/${{secrets.REGISTRY_NAME}}/${{ env.APPLICATION_NAME }}:${{ github.sha }}
          context: ${{env.APP_BUILD_CONTEXT}}
          file: ${{env.APP_DOCKERFILE}}
          build-args: ASPNETCORE_ENVIRONMENT=Staging
          
  deploy:
    runs-on: ubuntu-latest
    needs: build      
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth SDK
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Cloud run deploy
        run: |
          gcloud run deploy ${{ env.APPLICATION_NAME }} --image ${{ secrets.REGISTRY_BASE_URL }}/${{ secrets.GOOGLE_PROJECT_ID}}/${{secrets.REGISTRY_NAME}}/${{ env.APPLICATION_NAME }}:${{ github.sha }} \
          --region=europe-west1 --project=${{secrets.GOOGLE_PROJECT_ID}} --memory=1024M --min-instances=1 --max-instances=10 --cpu=2 --timeout=120 --port=${{ env.PORT }}

      - name: Cloud run serve traffic
        run: gcloud run services update-traffic ${{ env.APPLICATION_NAME }} --to-latest --platform=managed --region=europe-west1
    